version: "3.7"
# DEV: sh -c "npm i && npm run dev -- --port 3000"
# PROD: command: sh -c "npm i && npm run build && npm run start -- --port 3000"
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: matcha_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  matcha:
    build: ./matcha
    stdin_open: true
    tty: true
    container_name: matcha
    restart: on-failure
    env_file: .env
    volumes:
      - "${PWD}/matcha/matcha:/usr/src/app/"
    command: sh -c "npm i && npm run build && npm run start -- --port 3000"
    ports:
      - "8000:3000"
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
