version: "3.7"

services:
  mysql-db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    ports:
      - 3307:3307
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: "redis:5-alpine"

  matcha-front:
    build: ./matcha
    container_name: matcha-front
    env_file: .env
    volumes:
      - "${PWD}/matcha/matcha:/usr/src/app/"
    command: sh -c "npm i && npm run dev -- --port 3001"
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
      - redis
